rvm:
  # NOTE: do not use jruby-19mode otherwise some specs might fail
  # @see ruby/rack/application_spec.rb for an explanation on this
  #- jruby-18mode
  #- jruby-19mode
  - jruby
  - jruby-head
branches:
  only:
    - master
gemfile:
  - Gemfile
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
env:
  - JRUBY_OPTS="--1.8 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
  - JRUBY_OPTS="--1.9 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"