branches:
  only:
    - master
    - 1.1-stable
    - maintenance-1.1.13
rvm:
  # NOTE: do not use jruby-19mode otherwise some specs might fail
  # @see ruby/rack/application_spec.rb for an explanation on this
  #- jruby-18mode
  #- jruby-19mode
  - jruby
  #- jruby-head
gemfile:
  - Gemfile
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  #- gemfiles/rails41.gemfile
env:
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS"
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS"
#before_script: export JRUBY_OPTS="--server -Xcompile.invokedynamic=false"
before_install:
  - ((jruby -v | grep 1.8.7) && jruby --1.9 -S gem update --system 2.1.11) || true
  - ((echo $BUNDLE_GEMFILE | grep rails23) && jruby --1.9 -S gem update --system 1.8.29) || true
matrix:
  allow_failures:
    #- gemfile: gemfiles/rails41.gemfile
  exclude:
    - rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS"
    #- rvm: jruby
    #  gemfile: gemfiles/rails41.gemfile
    #  env: JRUBY_OPTS="--1.8 $JRUBY_OPTS"