rvm:
  - jruby
branches:
  only:
    - master
gemfile:
  - Gemfile
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
env:
  - JRUBY_OPTS="--1.8"
  - JRUBY_OPTS="--1.9"
before_install:
  - gem uninstall bundler -x
  - gem install bundler -v '~> 1.0.0'
